version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: docker/dev-backend.Dockerfile
    container_name: sls-backend-dev
    working_dir: /workspaces/project
    volumes:
      - ./:/workspaces/project:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=${QT_QPA_PLATFORM:-xcb}
      - QT_AUTO_SCREEN_SCALE_FACTOR=1
      - QT_ENABLE_HIGHDPI_SCALING=1
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/tmp}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-}
    network_mode: host
    command: bash -lc "sleep infinity"

  frontend:
    build:
      context: .
      dockerfile: docker/dev-frontend.Dockerfile
    container_name: sls-frontend-dev
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
    network_mode: host
    command: bash -lc "sleep infinity"

  tools:
    build:
      context: .
      dockerfile: docker/dev-tools.Dockerfile
    container_name: sls-dev-tools
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
    network_mode: host
    command: bash -lc "sleep infinity"
